name: Nimplex Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Upgrade pip
        run: pip install --upgrade pip

      - name: Install lapack and pcre
        run: sudo apt-get update && sudo apt-get install -y liblapack-dev libpcre3-dev

      - name: Install nim
        uses: iffy/install-nim@v5

      - name: Install radalloy
        run: pip install -e .

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/nimplex:${{ github.workspace }}/nimplex/utils
        run: python -m unittest discover -s tests